// Verbatim from the GSTC Hotel Standard v4.0 PDF (December 30, 2025): https://www.gstc.org/wp-content/uploads/GSTC-Hotel-Standard.pdf
// Includes the source's own wording quirks (e.g. A10 indicator 2). Correct only against the PDF, never by paraphrase.
import type { GstcCriterion } from "./gstc-hotel.ts";

export const GSTC_HOTEL_V4_CRITERIA: readonly GstcCriterion[] = [
  {
    id: "A1", section: "A", group: "Effective Sustainable Management and Communication", page: 3,
    title: "Sustainability Management System",
    statement: "The hotel operates under a documented sustainability management system proportional to its size and scope, ensuring that sustainability is managed in a systematic manner and continuous improvement is pursued.",
    indicators: [
      "The hotel has a written sustainability policy that outlines its main guiding principles and commitments across the pillars of sustainability defined in this standard. (See Guidelines)",
      "The policy is formally approved and communicated to all staff.",
      "The hotel maintains a sustainability management plan that is appropriate for its size and operations. (See Guidelines)",
      "The plan includes qualitative and/or quantitative targets for social, cultural, and environmental sustainability indicators.",
      "Targets are reviewed annually and updated as necessary.",
      "The hotel identifies potential sustainability risks as part of its sustainability management plan. (See Guidelines)",
      "The hotel allocates appropriate financial and human resources to support the implementation of the sustainability management plan.",
      "The hotel reviews the implementation of its sustainability management plan annually and updates it as needed based on the review findings. (See Guidelines)",
    ],
    guidance: [
      "1. The policy serves as the foundation for sustainability planning and actions.",
      "3. The plan is aligned with the hotel’s annual budget and staffing capacity, ensuring that sufficient resources are allocated to implementing sustainability actions and achieving targets.",
      "6. Risks include environmental, social, and cultural factors that may affect the hotel or be affected by it. The analysis identifies preventive measures and potential mitigation actions for each sustainability risk.",
      "8. The review of implementation assesses progress and identifies areas for improvement.",
    ],
  },
  {
    id: "A2", section: "A", group: "Effective Sustainable Management and Communication", page: 3,
    title: "Legal Compliance",
    statement: "The hotel complies with all relevant laws and regulations concerning social, cultural, and environmental matters, including health and safety standards, labor rights, child protection, the prevention of human trafficking and modern slavery, and animal welfare.",
    indicators: [
      "The hotel maintains an up-to-date register of all applicable local and national laws and regulations. (See Guidelines)",
      "The hotel develops, implements, and enforces internal policies and procedures to ensure compliance with all legal requirements. (See Guidelines)",
    ],
    guidance: [
      "1. Applicable laws and regulations may include human rights, labor rights, health and safety, land and property rights, environmental protection, waste management, child welfare, prevention of human trafficking and modern slavery, cultural heritage protection, and animal welfare. A legal register is maintained—digitally where possible—to support accessibility. Compliance is reviewed periodically and updated as needed. All structures on the hotel premises comply with applicable regulations related to natural area protection, environmental protection, and cultural heritage conservation. Compliance is reviewed periodically and updated as necessary. Land ownership and tenure rights are documented and reviewed periodically to ensure legal validity and the protection of local traditional and Indigenous community rights.",
      "2. Policies and procedures are supported by staff training, documented compliance checks, and corrective actions where required. The hotel maintains documented evidence of compliance, such as valid official certificates or approval documents issued by the relevant authority or authorities. In cases where specific regulations are not in place, the hotel ensures that all fire protection equipment is regularly inspected, tested, and properly maintained. Fire safety equipment includes alarms, extinguishers, and sprinklers. Additionally, the hotel establishes clear evacuation plans and routes, displays them prominently in guest areas and staff zones, and reviews them at regular intervals to ensure their accuracy and accessibility. Refer to the GSTC Clarification on Legal Compliance with National Health and Safety Requirements for GSTC Certification for additional clarification.",
    ],
  },
  {
    id: "A3", section: "A", group: "Effective Sustainable Management and Communication", page: 3,
    title: "Guest and Staff Welfare",
    statement: "The hotel takes measures to support the well-being of guests and staff by identifying potential hazards and responding to any concerns.",
    indicators: [
      "The hotel assigns a designated person to oversee occupational and guests’ health and safety. (See Guidelines)",
      "Relevant staff members participate in training or awareness sessions on prevention of hazards, emergency response, and crisis preparedness, either through programs offered by national authorities or through internally organized training.",
    ],
    guidance: [
      "1. The hotel may contract an external occupational health and safety professional or designate an internal staff member with relevant training (e.g., workplace hazard recognition, risk assessment, emergency response). Training is directly relevant to hotel operations and refreshed periodically. The hotel must keep facilities hazard-free, have good hygiene, adequate security, and proper emergency plans.",
    ],
  },
  {
    id: "A4", section: "A", group: "Effective Sustainable Management and Communication", page: 4,
    title: "Reporting and Communication",
    statement: "The hotel communicates its sustainability policy, actions, and performance to stakeholders, including guests, and seeks to engage their support.",
    indicators: [
      "The hotel communicates its sustainability policy to stakeholders, including staff, suppliers, and guests.",
      "The hotel publishes an annual sustainability report outlining its sustainability policy, goals, actions, and performance. (See Guidelines)",
      "The hotel’s sustainability report, whether prepared at the individual property, franchise, or corporate level, is presented in a format appropriate to its size, capacity, and intended audience. (See Guidelines)",
      "The hotel ensures that its sustainability report—or the relevant section of a corporate or portfolio-level report—is made publicly accessible online (e.g., website, social media) or through offline channels. (See Guidelines)",
      "The hotel collects and monitors sustainability data at intervals appropriate to its operations (e.g., monthly, quarterly, semiannually, or annually) to ensure accurate reporting and to support continuous improvement. (See Guidelines)",
      "The hotel provides opportunities for stakeholders—including guests, staff, suppliers, and local communities—to give feedback on its sustainability practices. (See Guidelines)",
    ],
    guidance: [
      "2. The report includes available quantitative data on key indicators such as energy and water use, solid waste generation, greenhouse gas (GHG) emissions, and responsible procurement practices, while ensuring that any information considered a trade secret or commercially sensitive remains confidential. The annual sustainability report provides year-over-year comparisons of performance based on qualitative and quantitative data and stakeholder feedback. In the first year of implementation, or where baseline data is not available, the report establishes an initial baseline for future comparison.",
      "3. Larger establishments are encouraged to align reporting with recognized frameworks such as GRI or CSRD. Smaller hotels may adopt simplified approaches proportional to their scale and regional context. Where reporting occurs at the portfolio or corporate level, individual property performance—including franchise properties—is clearly distinguished.",
      "4. Information is accessible to guests, staff, suppliers, local community members, and other stakeholders upon request.",
      "5. Data stored in written or digital form is shared with third parties only when confidentiality and applicable legal requirements are upheld.",
      "6. Feedback mechanisms may be included in the hotel’s annual sustainability report and/or implemented through various channels (e.g., email, online forms, comment boxes, post-stay surveys).",
    ],
  },
  {
    id: "A5", section: "A", group: "Effective Sustainable Management and Communication", page: 4,
    title: "Accurate Promotion",
    statement: "The hotel ensures that all promotional materials and marketing communications are transparent and verifiable, accurately representing its offerings, facilities, accommodation type, service standards, and sustainability commitments without any misleading claims.",
    indicators: [
      "The hotel ensures that all promotional materials, including media and on-site signage, accurately represent its facilities and services.",
      "The hotel ensures that promotional materials accurately represent its sustainability practices and commitments. All claims are based on actual practices and supported by verifiable data or documentation. (See Guidelines)",
      "The hotel provides transparent and easily accessible information about its sustainability commitments through its website, annual sustainability reports, or other public platforms (e.g., social media or brochures).",
    ],
    guidance: [
      "2. Claims do not exaggerate, generalize, imply commitments, or reference actions that are not being actively implemented.",
    ],
  },
  {
    id: "A6", section: "A", group: "Effective Sustainable Management and Communication", page: 4,
    title: "Information Sharing and Guidance",
    statement: "The hotel provides information on the natural and cultural characteristics of the area and explains appropriate behavior when visiting natural or cultural sites.",
    indicators: [
      "The hotel provides training for its staff on the destination’s natural environment, local culture, and heritage.",
      "The hotel makes information about the destination’s natural environment, local culture, and heritage readily available to its guests. (See Guidelines)",
      "The hotel provides documented behavioral guidelines for staff to promote respectful conduct both within the hotel and in the surrounding community, and to communicate this information to guests. (See Guidelines)",
      "The hotel provides documented guidelines encouraging respectful behavior within the hotel, the surrounding community, and during excursions, tours, or activities.",
      "The hotel prioritizes environmentally responsible methods for sharing information, including the use of digital formats. (See Guidelines)",
      "The hotel makes information available in languages that are relevant and understandable to both staff and guests.",
      "The hotel provides information in accessible formats when necessary. These formats accommodate people with disabilities and may include large print, audio versions, or screen-reader-compatible digital content.",
    ],
    guidance: [
      "2. Priority is given to sharing information through sustainable formats, such as digital materials (e.g., QR codes, apps), signage or displays, in-room media, or trained staff briefings.",
      "3. Guidelines aim to prevent behaviors that may negatively impact the environment, local culture, communities, children, hotel staff, or other guests. Where available, guidelines provided by destination authorities are used.",
      "5. Digital formats include QR codes, online guides, and mobile apps where appropriate. Where digital formats do not enhance the guest experience, low-impact alternatives—such as personal briefings or durable, reusable materials—are encouraged.",
    ],
  },
  {
    id: "A7", section: "A", group: "Stakeholder Engagement", page: 5,
    title: "Staff Engagement",
    statement: "The hotel involves its staff in the development, implementation, and continuous improvement of its sustainability management system. Staff receive structured training, ongoing support, and recognition for their contributions to sustainability.",
    indicators: [
      "The hotel engages staff in developing and implementing the sustainability policy and related action plans. (See Guidelines)",
      "Staff have clearly defined roles and responsibilities for implementing the hotel’s sustainability policy and action plans. (See Guidelines)",
      "The hotel provides staff with orientation and structured sustainability training to ensure understanding of sustainability basics and their roles. (See Guidelines)",
      "The hotel maintains records of training sessions or guidance, such as attendance lists and training materials.",
      "The hotel ensures that training and reference materials are available in languages understood by all relevant staff to ensure inclusivity and accessibility, particularly for those who are not fluent in the primary working language.",
      "The hotel supports staff in obtaining the necessary job-related certifications, qualifications, or equivalent training needed for their roles and responsibilities.",
      "The hotel regularly reviews and documents staff engagement and feedback to strengthen staff participation and continuous improvement.",
    ],
    guidance: [
      "1. Engagement may take place through consultation methods such as feedback sessions, informal meetings, structured committees, or digital platforms (e.g., staff mobile apps or corporate feedback systems), depending on the property’s size and organizational structure.",
      "2. In larger hotels, specific sustainability tasks may be assigned to dedicated staff or departments, with roles reviewed periodically. In smaller hotels, responsibilities may be integrated into existing roles (e.g., management, housekeeping, front desk), with at least one person designated to oversee implementation of the sustainability management plan.",
      "3. Orientation and training programs may include GSTC hotel training or an equivalent program.",
    ],
  },
  {
    id: "A8", section: "A", group: "Stakeholder Engagement", page: 5,
    title: "Guest Experience",
    statement: "The hotel monitors guest satisfaction, including feedback on sustainability and responsible practices, and strives for continuous improvement.",
    indicators: [
      "The hotel maintains a guest feedback system.",
      "The hotel regularly collects and reviews positive and negative feedback using methods appropriate to its size and type. (See Guidelines)",
      "The hotel takes and documents corrective actions in response to identified issues, complaints, or nonconformities.",
      "The hotel notifies guests about the corrective actions.",
      "The hotel engages guests in sustainability practices by providing clear guidance and opportunities for participation.",
    ],
    guidance: [
      "2. Feedback methods may include online platforms, in-room materials, and staff interactions. Feedback is used to improve the hotel’s sustainability management plan and guest experience.",
    ],
  },
  {
    id: "A9", section: "A", group: "Stakeholder Engagement", page: 6,
    title: "Collaboration with Stakeholders",
    statement: "The hotel collaborates with relevant stakeholders to support and contribute to sustainable tourism development within its destination.",
    indicators: [
      "The hotel maintains documented engagement with relevant local stakeholders, such as destination management organizations (DMOs), NGOs, tourism boards, community leaders, cooperatives, or local tourism-related associations, to align its sustainability goals with broader community and destination priorities. (See Guidelines)",
    ],
    guidance: [
      "1. Engagement may include participating in joint planning meetings, supporting local tourism initiatives, co-developing community projects, or promoting local products and cultural heritage. The hotel considers and, where feasible, applies mutually agreed outcomes from stakeholder engagement processes in proportion to the property’s size and capacity.",
    ],
  },
  {
    id: "A10", section: "A", group: "Buildings and Infrastructure", page: 6,
    title: "Land, Water, and Property Rights",
    statement: "The hotel acquires land, water, and property rights through legal and ethical means, respecting local, communal, and Indigenous rights. Free, prior, and informed consent is obtained when applicable and any potential negative impacts on local communities are identified and appropriately addressed.",
    indicators: [
      "The hotel ensures all necessary legal documentation is in place for access to and use of key resources, such as land and water.",
      "For new development projects, expansions, or major renovations, the hotel demonstrates that consultation has taken place with affected residents from local, traditional, or Indigenous communities, as well as relevant NGOs, to identify, to identify and address potential impacts associated with the project. (See Guidelines)",
      "For new developments or land acquisition projects in areas where traditional and/or Indigenous communities may be affected, the hotel complies with all applicable regulations. In the absence of such regulations, the hotel follows the principles of Free, Prior, and Informed Consent (FPIC) in consultation with affected communities.",
      "The hotel ensures a grievance mechanism is available for external stakeholders, such as residents, neighbors, or local organizations, to raise concerns related to its operations or development, including land, water, or property rights.",
      "The hotel’s annual sustainability report confirms that land and water use comply with all applicable legal requirements and any established agreements.",
    ],
    guidance: [
      "2. Consultation processes are carried out in culturally appropriate ways that respect local customs, traditions, and practices.",
    ],
  },
  {
    id: "A11", section: "A", group: "Buildings and Infrastructure", page: 6,
    title: "Site Selection, Planning, and Development",
    statement: "The site selection, planning, and development of hotel facilities and associated activities take into account environmental carrying capacity, cultural integrity, and social impact. This applies to all new constructions, additions, alterations, upgrades, and refurbishments of existing facilities.",
    indicators: [
      "For new developments, expansions, or major renovations, the hotel obtains all required site selection, planning, and construction licenses and permits in line with applicable legal requirements and procedures. (See Guidelines)",
      "For new developments, expansions, or major renovation projects, the hotel conducts assessments of sustainability-related risks—such as environmental impacts— as an integral part of the planning process. (See Guidelines)",
      "For new developments, expansions, or major renovations, site selection, design, and access are planned to protect the surrounding landscape and cultural, natural, or heritage sites. When necessary, the hotel consults with local authorities and communities to identify and implement safeguarding measures. (See Guidelines)",
      "For new developments, expansions, or major renovations located near protected or sensitive natural areas, the hotel implements measures during planning and construction to prevent disruption of landscape and ecosystem connectivity. These measures include preserving key landscape features, wildlife corridors, and access routes that link surrounding natural areas.",
    ],
    guidance: [
      "1. The hotel maintains valid and up-to-date documentation of all relevant approvals (see A2.1).",
      "2. Potential impacts of developments, expansions, or renovations on threatened or protected species are evaluated through appropriate environmental assessments or due diligence.",
      "3. The hotel protects surrounding landscapes and any cultural, natural, or heritage sites, including sacred places, during site selection, planning, and development.",
    ],
  },
  {
    id: "A12", section: "A", group: "Buildings and Infrastructure", page: 7,
    title: "Buildings, Construction, and Infrastructure",
    statement: "The development and maintenance of hotel buildings, infrastructure, and construction activities respect integrated local culture, ecosystems, and biodiversity, ensuring minimal environmental and social impact. This applies to all new constructions, additions, alterations, and upgrades.",
    indicators: [
      "The hotel gives preference to, where feasible, the use of qualified local labor —defined by residency and legal work status—in construction, expansion, and development projects. (See Guidelines)",
      "Where new construction, renovations, or expansions take place, the hotel gives preference to the use of locally sourced construction methods and materials, as well as low-impact options or those certified under recognized sustainability standards.",
      "Where construction, expansion, or major renovation is ongoing, the hotel implements effective measures to manage and reduce runoff, ensuring that soil, debris, and pollutants are properly captured and filtered to prevent environmental contamination.",
      "Where construction, expansion, or major renovation is ongoing, the hotel ensures that nearby watercourses, wetlands, and catchment areas are not negatively impacted by construction activities. Where applicable, the hotel implements design measures to minimize surface runoff and preserve natural water flow.",
      "The hotel prioritizes the use of native or endemic plant species in landscaping and decoration to support local biodiversity. In all cases, invasive species are avoided. (See Guidelines)",
      "Where construction, expansion, or major renovation is ongoing, the hotel manages construction waste in an environmentally responsible manner, following a hierarchy of priorities: reducing waste generation, reusing materials, and recycling or upcycling whenever possible.",
    ],
    guidance: [
      "1. Local sourcing aims to support the local economy and reduce environmental impacts through shorter supply chains.",
      "5. Where native options are unavailable or not resilient (e.g., drought conditions), the hotel selects non-invasive, climate-resilient species appropriate to the property’s context.",
    ],
  },
  {
    id: "A13", section: "A", group: "Responsible Procurement", page: 8,
    title: "Procurement",
    statement: "The hotel implements a responsible procurement policy that gives preference to local, fair-trade, and environmentally friendly products and services, thereby minimizing environmental impacts and maximizing local community benefits throughout the procurement process.",
    indicators: [
      "The hotel has a written procurement policy that gives preference to fair, local, and environmentally friendly products and services used in its operations.",
      "The hotel establishes targets for procurement categories with significant environmental or social impacts. (See Guidelines)",
      "The hotel establishes targets to purchase products and services that are locally produced and supplied by businesses located within or near the destination where it operates, whenever they are available, legally compliant, and of sufficient quality. (See Guidelines)",
      "When local procurement is not possible, the hotel gives preference to products sourced from fair-trade suppliers, cooperatives, or other vendors that demonstrate ethical and responsible sourcing practices. (See Guidelines)",
      "The procurement policy follows circular economy principles by prioritizing reusable, returnable, and recycled materials—including takeaway food and beverage packaging or plastic items—and giving preference to disposable items made from recycled and/or recyclable materials when their use cannot be avoided.",
      "The hotel takes measures to eliminate single-use items through documented policies and procedures within procurement. (See Guidelines)",
      "The hotel ensures that all hotel signage, marketing materials, and promotional items are either electronic, reusable, or printed on recycled or recyclable materials, ensuring that they are environmentally friendly and, where possible, locally sourced.",
      "The hotel does not purchase, sell, or use products derived from species listed as vulnerable, threatened or endangered, in compliance with applicable local and national laws and internationally recognized conservation standards.",
      "The hotel monitors procurement practices using key performance indicators, such as the percentage of goods and services sourced locally, the proportion of items that are environmentally friendly, or the percentage obtained through fair-trade and other verified responsible channels.",
      "The hotel integrates sustainability indicators into supplier evaluation processes.",
      "The hotel gives preference to suppliers who take and document steps to reduce their environmental impact. (See Guidelines)",
      "The hotel’s agreements with suppliers, where applicable, include sustainability-related requirements appropriate to the products or services being provided. (See Guidelines)",
      "The hotel reviews supplier compliance at a minimum during the supplier selection process and at each contract renewal, where applicable. (See Guidelines)",
      "The hotel conducts due diligence to ensure that suppliers providing products sourced from the wild comply with all applicable local, national, and—where relevant—international regulations related to wildlife harvesting and trade.",
    ],
    guidance: [
      "Note: “Local” refers to the destination and its surrounding area, as defined by relevant authorities or common regional practice. Traders or resellers who primarily provide goods from outside the destination are not considered local suppliers.",
      "2. Categories may include seafood, textiles, chemicals, wood and paper products, and sugar. Specific targets are set and tracked. For seafood, procurement is—where possible—from sources certified by recognized sustainability standards (e.g., MSC, ASC), with documented origin. If performance declines, the hotel provides documented explanations.",
      "3. The hotel sets a target to source at least 25% of fresh goods (by expenditure volume) from local producers and/or suppliers. KPIs are reported in the annual sustainability report.",
      "4. Examples of fair-trade products include tea, coffee, cocoa, cotton, sugar, spices, fruit, and similar items.",
      "6. Step-by-step reduction of single-use items:\nSingle-use plastics:\n• The hotel eliminates single-use plastics (e.g., straws, stirrers, water bottles, PP/EPS containers, plastic/PFAS packaging for dry amenities) and replaces them with reusable alternatives wherever possible.\n• Where immediate elimination is not feasible, the hotel establishes a time-bound reduction plan.\nSingle-use amenities:\n• The hotel phases out single-use guest amenities (e.g., shampoo, soap) except where legally required, replacing them with refillable or bulk alternatives.\n• Additional reduction practices may include bulk purchasing, reducing single-use plastics, switching to reusable trolley covers, phasing out Styrofoam, conducting waste audits, and collaborating with suppliers on recycling or return systems.",
      "11. Steps may include minimizing packaging, conserving energy, and using low-impact delivery methods. Indicators form part of supplier evaluations.",
      "12. Requirements cover environmental, social, and ethical aspects such as resource use, fair labor, and responsible practices.",
      "13. Reviews may be conducted through basic screening methods, including sustainability aspects, or through sampled evaluations.",
    ],
  },
  {
    id: "A14", section: "A", group: "Responsible Procurement", page: 9,
    title: "Food and Beverages",
    statement: "The hotel promotes and provides environmentally and socially responsible food and beverage options, prioritizing locally sourced, organic, plant-based, and ethically produced alternatives, while implementing food waste reduction and sustainable service practices.",
    indicators: [
      "The hotel offers dining services that include plant-based, vegetarian, and/or vegan options. Where feasible, each course (starter, main, dessert, if applicable) features at least one clearly labeled plant-based dish. (See Guidelines)",
      "The hotel recommends or promotes nearby food and beverage providers that demonstrate sustainable sourcing practices, including those certified to recognized sustainability standards, if the hotel does not offer food and beverage service.",
      "The hotel gives preference to the purchase of plant-based ingredients that are locally produced, and/or certified to recognized sustainability standards—such as organic, fair-trade, or equivalent.",
      "The hotel implements practices in kitchens, buffet, and dining areas to encourage responsible management and consumption and to reduce food waste. (See Guidelines)",
    ],
    guidance: [
      "Note: Environmentally and socially responsible food includes products certified by recognized sustainability standards (e.g., organic, fair trade, MSC/ASC) and locally produced items. Dishes may be labeled “sustainable” or “environmentally/socially responsible” only when they meet clearly defined criteria aligned with the hotel’s sourcing policy.",
      "1. Where applicable and environmentally feasible, the hotel assesses the availability of plant-based dishes and establishes KPIs to maintain or improve variety and visibility.",
      "4. Practices may include buffet design, avoiding overproduction, portion control, guest communication, food waste measurement, and staff engagement.",
    ],
  },
  {
    id: "B1", section: "B", group: "Social and Economic Benefits to the Community", page: 10,
    title: "Community support",
    statement: "The hotel supports the local community through structured initiatives that address community needs, foster inclusive development, and promote sustainable economic and social benefits.",
    indicators: [
      "The hotel provides ongoing financial or in-kind support to the local community and the relevant projects. (See Guidelines)",
      "The hotel records and monitors the level and nature of contributions made to the community. (See Guidelines)",
      "The hotel offers cooperation or skills-development programs specifically aimed at increasing the employability of local community members where feasible and appropriate to its size. (See Guidelines)",
    ],
    guidance: [
      "1. Community support may be provided in areas such as infrastructure, cultural rehabilitation, education, training, small business development, health, sanitation, or emergency response. Contributions should form part of sustained relationships or programs, rather than one-time donations.",
      "2. Support may be based on the hotel’s sustainability policy, which outlines objectives and priority initiatives aligned with community needs identified through community feedback.",
      "3. The hotel may collaborate with educational institutions, vocational training centers, or employment agencies to enhance local employability.",
    ],
  },
  {
    id: "B2", section: "B", group: "Social and Economic Benefits to the Community", page: 10,
    title: "Local Employment",
    statement: "The hotel provides fair and equitable opportunities for local residents to obtain employment and advance within the organization, including into leadership and management roles.",
    indicators: [
      "The hotel maintains a written policy committing to provide fair and equitable employment opportunities to local residents who meet job-related qualifications, including the required skills, experience, or certifications.",
      "The hotel implements its policy through transparent and inclusive recruitment practices for both permanent and temporary staff. (See Guidelines)",
      "The hotel monitors the proportion of local staff within its overall workforce, including those in management and supervisory positions.",
      "The hotel gives preference to suppliers who support local employment.",
    ],
    guidance: [
      "2. The hotel may consider specific actions to attract qualified local candidates across job levels.",
    ],
  },
  {
    id: "B3", section: "B", group: "Social and Economic Benefits to the Community", page: 10,
    title: "Local Entrepreneur Support",
    statement: "The hotel supports local entrepreneurs and community- or nonprofit-owned businesses in developing, improving, or selling their products and services. This initiative aims to strengthen the local economy and promote sustainable business practices.",
    indicators: [
      "Where appropriate, the hotel supports local entrepreneurs and community- or nonprofit organization-owned businesses in developing or improving products and services that reflect the destination’s nature, history, or culture, and it maintains a list of the products and services it supports. (See Guidelines)",
      "The hotel promotes the products and services of local entrepreneurs and community- or nonprofit organization-owned businesses to its guests. (See Guidelines)",
    ],
    guidance: [
      "1. The hotel may support local entrepreneurs and community or nonprofit organizations by providing basic guidance, training, and opportunities to participate in development initiatives. These efforts aim to enhance the quality, safety, and sustainability of entrepreneur products and services, with guest feedback considered.",
      "2. Where possible, the hotel may offer promotional opportunities, such as free display or sales space, and market local products and services. Events or digital showcases may also be used.",
    ],
  },
  {
    id: "B4", section: "B", group: "Social and Economic Benefits to the Community", page: 11,
    title: "Community Services and Livelihoods",
    statement: "The hotel ensures that its operations and commercial activities do not adversely impact local community services, livelihoods, or access to essential resources.",
    indicators: [
      "The hotel’s operations do not restrict local communities’ access to essential livelihoods. (See Guidelines)",
      "The hotel’s operations do not impede local access to rights-of-way and transportation routes, thereby preserving community mobility.",
      "The hotel’s activities do not restrict access to local residences or limit community members’ ability to reach their homes.",
      "The hotel has a system in place for local communities to address grievances. (See Guidelines)",
      "The hotel documents reported issues and addresses them promptly, sharing outcomes with relevant stakeholders as needed.",
    ],
    guidance: [
      "1. Essential livelihoods may include access to land and aquatic resources that support community members’ daily and traditional practices.",
      "4. The hotel provides a well-publicized, accessible communication channel for community members to raise concerns related to access limitations caused by hotel operations. Examples may include restricted access to public paths, beaches, roads, or culturally significant sites.",
    ],
  },
  {
    id: "B5", section: "B", group: "Social and Economic Benefits to the Community", page: 11,
    title: "Access for All",
    statement: "The hotel ensures that its site, facilities, and services are accessible to people of all abilities to the greatest extent possible, committing to progressive improvements that meet their needs. Comprehensive, accurate, and reliable information on accessibility features, limitations, and services is provided.",
    indicators: [
      "Where possible and practicable, the hotel ensures that key areas of its premises are accessible and inclusive for people with diverse physical (mobility, vision, and hearing) and neurodivergent (sensory and cognitive) access needs.",
      "The hotel demonstrates ongoing improvements in accessibility for individuals with diverse needs by maintaining plans or strategies for continuous improvement. (See Guidelines)",
      "The hotel provides clear and specific details on its accessibility features and how guests can request related services prior to booking and before arrival.",
      "The hotel provides communication materials for guests with diverse abilities in accessible formats to ensure clarity and usability.",
      "The hotel includes people with disabilities in the creation, execution, and improvement of accessibility features and services.",
      "The hotel goes beyond local accessibility laws by ensuring that furniture selection and placement support accessibility.",
    ],
    guidance: [
      "2. Individuals with diverse needs include, but are not limited to: people with mobility, visual, or hearing impairments; individuals with cognitive, sensory, or neurodivergent conditions; those with temporary impairments such as injuries or post-surgery limitations; individuals with allergies or specific dietary requirements; pregnant or nursing mothers; and elderly customers.",
    ],
  },
  {
    id: "B6", section: "B", group: "Human Resources and Ethical Standards", page: 11,
    title: "Code of Conduct",
    statement: "The hotel has a written code of conduct to guide the behavior and actions of staff, suppliers, and guests.",
    indicators: [
      "The hotel maintains a written code of conduct that includes a zero-tolerance policy toward any form of exploitation, harassment, abuse, or human trafficking, in line with internationally recognized frameworks. (See Guidelines)",
      "The code includes clear guidelines on respectful communication for both verbal and non-verbal behavior.",
      "The code contains clear guidelines and safeguards to prevent inappropriate interactions with minors, including guest and community children, youth, students, and interns. (See Guidelines)",
      "The code includes clear guidance to ensure respectful and non-discriminatory interactions with individuals from vulnerable or marginalized groups, such as persons with disabilities, older adults, or those experiencing social exclusion. (See Guidelines)",
      "The code is communicated to all staff and regularly updated.",
      "The hotel provides regular training and guidance on the code of conduct to all staff, maintaining records for review and verification. (See Guidelines)",
    ],
    guidance: [
      "1. Internationally recognized frameworks may include the UN Convention on the Rights of the Child, ILO Conventions on Forced and Child Labor, and the UN Guiding Principles on Business and Human Rights.",
      "3. The hotel contributes to efforts to prevent exploitation and abuse of children (defined as individuals under age 18), with special attention to protecting those below the legal working age. The hotel verifies the identification of all guests at check-in, including children and accompanying adults, and retains records in accordance with legal and privacy requirements.",
      "4. Guidelines ensure respectful conduct, adherence to safeguarding practices, and appropriate personal interactions.",
      "6. Behavioral expectations, anti-discrimination standards, and safeguarding principles are communicated to guests and incorporated into supplier agreements, so all parties are informed.",
    ],
  },
  {
    id: "B7", section: "B", group: "Human Resources and Ethical Standards", page: 12,
    title: "Exploitation, Harassment, and Human Trafficking",
    statement: "The hotel implements a comprehensive zero-tolerance policy against all forms of exploitation, harassment, and human trafficking—including forced labor—and provides enhanced protection for vulnerable groups such as children (minors), adolescents, women, Indigenous peoples, minorities, people with disabilities, and other vulnerable populations.",
    indicators: [
      "The hotel has a written policy that outlines procedures for identifying, monitoring, reporting, ensuring confidential disclosure, and responding to incidents of exploitation, harassment, and human trafficking, as well as for preventing child labor. (See Guidelines)",
      "The hotel communicates its policy both internally and externally to stakeholders, including staff, guests, and suppliers directly involved in hotel operations. (See Guidelines)",
      "The hotel monitors the implementation of the policy and procedures to ensure compliance.",
      "The hotel provides staff with guidance and training on recognizing and reporting incidents of exploitation and harassment.",
      "The hotel maintains records demonstrating that no child labor or illegal labor is employed.",
      "The hotel requires suppliers to comply with this policy and incorporates these requirements into supplier selection, contracts, communications, and ongoing evaluations.",
    ],
    guidance: [
      "1. The policy ensures that barriers to reporting are addressed by providing clear, accessible, and confidential channels for raising concerns, and it requires swift action and accountability in all cases of violation. It may also reference internationally recognized frameworks such as the UN Convention on the Rights of the Child, the ILO Conventions on Forced and Child Labor, and the UN Guiding Principles on Business and Human Rights, as well as practical voluntary initiatives such as The Code (The Code of Conduct for the Protection of Children from Sexual Exploitation in Travel and Tourism), which offers tools and support for implementing effective child protection measures.",
      "2. Internal communication may occur through onboarding, staff handbooks, or management policies; external communication may include guest care charters, purchasing policies, and supplier contracts.",
    ],
  },
  {
    id: "B8", section: "B", group: "Human Resources and Ethical Standards", page: 12,
    title: "Employment Inclusion and Equality",
    statement: "The hotel provides inclusion and equal employment opportunities at all levels and for all positions. Its employment policy explicitly prohibits discrimination on the basis of any non–merit-based characteristics.",
    indicators: [
      "The hotel has a written inclusive employment policy that explicitly prohibits discrimination based on gender, age, race, nationality, ethnic origin, color, religion, sexual orientation, gender identity or expression, marital or family status, genetic characteristics, disability, or any other non-merit-based factor.",
      "The hotel regularly reviews and updates the policy as needed.",
      "The hotel identifies and documents groups at risk of discrimination and reflects this awareness in its employment and HR practices, acknowledging all relevant non-merit-based characteristics. (See Guidelines)",
      "The hotel provides training to staff on recognizing, preventing, and addressing bias and discrimination in the workplace and in guest interactions.",
      "The hotel monitors the implementation of equal employment opportunities across all positions — including management roles.",
    ],
    guidance: [
      "3. Risk groups may include women, persons with disabilities, Indigenous peoples, local minorities, and others depending on the local context.",
    ],
  },
  {
    id: "B9", section: "B", group: "Human Resources and Ethical Standards", page: 13,
    title: "Decent Work",
    statement: "The hotel upholds labor rights by ensuring a safe and secure working environment, providing a living wage, and offering regular training and opportunities for career advancement. This commitment applies to both directly employed staff and outsourced workers, with measures in place to protect vulnerable workers from exploitation.",
    indicators: [
      "The hotel complies with all relevant national labor regulations ensuring a safe and secure working environment for all staff, including those hired by contracted organizations involved in its operations. Additionally, it complies with International Labour Organization (ILO) conventions and standards where applicable. (See Guidelines)",
      "The hotel provides all directly employed staff access to health, medical, and social security provisions in line with national legislation and employment frameworks. (See Guidelines)",
      "The hotel ensures that all staff, including contract and temporary staff, receive at least the legal minimum wage required by national or local labor laws. (See Guidelines)",
      "The hotel implements an annual review process for staff wages, designed to provide salary adjustments based on measurable criteria, such as performance, tenure, and skill development. (See Guidelines)",
      "The hotel offers appropriate training related to staff roles, professional development, and clear pathways for advancement or job enlargement. Training records are maintained for all staff, demonstrating the level and frequency of training received.",
      "The hotel monitors and records staff satisfaction through regular surveys or feedback mechanisms.",
      "The hotel has a system in place for staff to raise and address grievances safely and confidentially, with explicit safeguards to ensure there is no retaliation or negative consequences for using the system.",
    ],
    guidance: [
      "1. Hotels are encouraged to clearly define responsibilities and ensure that high-risk or specialized contractors comply with safety procedures, equipment requirements, and legal obligations.",
      "2. Where health, medical, or social security provisions are not provided through public systems, staff contracts may include required provisions.",
      "3. In contexts without a legal minimum wage, the hotel seeks to align compensation with recognized living wage benchmarks (e.g., the IDH Salary Matrix), applying this requirement to relevant suppliers and partners.",
      "4. The review process, including career preferences and performance, is documented and used to improve staff remuneration.",
    ],
  },
  {
    id: "C1", section: "C", group: undefined, page: 14,
    title: "Cultural Interactions",
    statement: "The hotel informs its guests and staff about local culture, ensuring culturally respectful interactions. A communication mechanism is in place to address concerns from local communities and Indigenous peoples, with corrective actions implemented as needed.",
    indicators: [
      "The hotel provides guests with educational or interpretive materials on the destination’s culture and tangible and intangible cultural heritage to ensure culturally respectful interactions. (See Guidelines)",
      "The hotel provides staff in guest-facing roles—such as front office, guest services, concierge, and food and beverage—with guidance, training, and resources on local customs, traditions, and etiquette to promote culturally respectful interactions. Other staff receive general awareness training as appropriate to their roles.",
      "The hotel maintains a communication channel through which local communities or Indigenous peoples can raise concerns or report negative impacts related to the hotel’s operations or guest activities.",
      "The hotel reviews and addresses all feedback on cultural interactions. (See Guidelines)",
    ],
    guidance: [
      "1. The hotel may collaborate with local or Indigenous communities to co-create and validate cultural representations in guest experiences, storytelling, and promotional materials. For materials provided by third parties (e.g., tour guides), the hotel verifies appropriateness.",
      "4. The mechanism helps identify potential impacts and address known issues; all feedback is reviewed and responded to respectfully.",
    ],
  },
  {
    id: "C2", section: "C", group: undefined, page: 14,
    title: "Protecting Cultural Heritage",
    statement: "The hotel contributes to protecting and enhancing cultural heritage with historical, archaeological, traditional, and spiritual significance and does not impede local residents’ access.",
    indicators: [
      "The hotel contributes to protecting and enhancing local cultural heritage by providing financial contributions, in-kind resources, and/or by engaging in collaborative efforts with relevant stakeholders.",
      "The hotel ensures that its operations do not impede local residents’ access to cultural heritage sites.",
    ],
    guidance: [],
  },
  {
    id: "C3", section: "C", group: undefined, page: 14,
    title: "Presenting Culture and Heritage",
    statement: "The hotel values and integrates authentic elements of traditional and contemporary local culture into its operations, design, decoration, cuisine, or shops, while respecting all intellectual property rights.",
    indicators: [
      "The hotel integrates art, crafts, or design elements that are produced by local artisans or created within the destination into its public and guest-facing spaces. (See Guidelines)",
      "Where applicable, the hotel incorporates cultural heritage elements (e.g., traditional music, dance, food, performance, and crafts) into its operations, ensuring legal compliance.",
      "The hotel respects intellectual property rights by obtaining the necessary permissions for cultural presentations, such as music, artwork, designs, traditional crafts, or performances.",
      "When presenting cultural heritage elements that are sensitive, traditional, or specific to Indigenous, minority, or underrepresented groups, the hotel consults relevant local experts, NGOs, or representatives of the communities concerned to ensure accuracy, respect, and appropriate representation.",
    ],
    guidance: [
      "1. All items are presented with authenticity and proper attribution to their creators.",
    ],
  },
  {
    id: "C4", section: "C", group: undefined, page: 15,
    title: "Artifacts",
    statement: "Artifacts are not sold, traded, or displayed except as permitted by applicable local and international laws.",
    indicators: [
      "The hotel complies with all relevant local and international laws and conventions when using artifacts. (See Guidelines)",
      "The hotel maintains an internal inventory of any artifacts in its possession, documenting their origin, use and display, and legal ownership or custody. (See Guidelines)",
    ],
    guidance: [
      "1. The artifacts policy outlines procedures for verifying the legal origin of cultural items and is communicated to relevant staff and suppliers. Where required, official permits or licenses are obtained, documented, and made available upon request.",
      "2. Guidance may include instructions to prevent removal, damage, or defacement of artifacts on hotel premises or in surrounding areas, communicated through signage, staff briefings, or guest materials.",
    ],
  },
  {
    id: "D1", section: "D", group: "Conserving Resources", page: 16,
    title: "Energy Conservation",
    statement: "The hotel measures and monitors its energy use and implements measures to reduce consumption across its operations, while increasing the use of renewable energy.",
    indicators: [
      "The hotel measures total energy use across its operations and energy use per guest night or per occupied room, by energy type. (See Guidelines)",
      "The hotel uses renewable energy sources where available and reports the source and proportion of renewable energy generated on-site or purchased externally in its annual sustainability report.",
      "The hotel sets annual targets to reduce overall energy consumption and increase the share of renewable energy and tracks its progress annually. (See Guidelines)",
      "The hotel takes practical steps to reduce energy use. This includes using energy-saving lights and appliances, improving heating and cooling systems with effective temperature control and insulation, using natural ventilation where possible, and ensuring that lights, equipment, and vehicles are turned off when not in use. (See Guidelines)",
      "The hotel conducts regular maintenance of energy and water equipment—including HVAC systems, refrigeration units, boilers, and other major appliances—to ensure optimal efficiency and performance. (See Guidelines)",
      "The hotel reduces the use of non-renewable fuels in all outdoor heating and cooling operations to the highest extent achievable. (See Guidelines)",
      "The hotel provides training or guidance on energy-saving practices to on-site contractors and staff.",
      "The hotel communicates with guests about its energy policy and practices.",
    ],
    guidance: [
      "1. Examples include gas, electricity, and transportation fuel used in directly managed hotel operations.",
      "3. Targets for renewable energy use are based on technical, financial, and operational feasibility and local grid availability. The hotel identifies opportunities for on-site renewable energy and documents constraints where adoption is not currently possible. Renewable energy consumption is reported annually.",
      "4. Energy performance is evaluated regularly to identify savings opportunities. Targets and results are reported annually, with property-level data clearly distinguished from corporate or portfolio reporting.\nEnergy-Saving Practices:\n• LED Lighting: The hotel prioritizes the use of energy-efficient lighting, such as LED bulbs. Failed or outdated fixtures are replaced with energy-saving alternatives, and targets are set to progressively increase the share of energy-efficient lighting in line with the property’s infrastructure, feasibility, and sustainability goals.\n• Guest rooms with heating or air conditioning (HVAC) systems are equipped with room-level automation or guest-controlled energy-saving mechanisms, such as keycard switches, motion sensors, or smart thermostats. Where full implementation requires major system upgrades, the hotel adopts a phased, multiyear transition plan. Interim measures—such as guest awareness programs, manual controls, or partial retrofitting—are encouraged until full compliance is achieved.",
      "5. Maintenance includes scheduled inspections, cleaning, calibration, and timely replacement of faulty components, with records maintained as evidence of compliance.",
      "6. For outdoor heating and cooling, the hotel indicates the energy source, consistent with the hotel’s energy policy.",
    ],
  },
  {
    id: "D2", section: "D", group: "Conserving Resources", page: 16,
    title: "Water Conservation",
    statement: "The hotel measures and monitors its water use and implements measures to reduce consumption across its operations, pursuing appropriate stewardship goals particularly in areas of high-water risk.",
    indicators: [
      "The hotel has identified and documented the water risk level in its destination using credible sources or frameworks. (See Guidelines)",
      "The hotel ensures that its water supply originates from legally compliant sources that do not adversely affect local environmental flows.",
      "The hotel measures total water use in overall operations by source (e.g., municipal supply, groundwater, seawater) and measures water use per guest night or per occupied room.",
      "The hotel sets annual targets to reduce water consumption and tracks its progress annually. (See Guidelines)",
      "The hotel focuses on water-efficient equipment (e.g., low-flow fixtures for faucets, showerheads, toilets, and appliances), while enhancing water-saving practices in its operations.",
      "The hotel utilizes water efficiently in outdoor operations, such as plant watering and cleaning procedures, ensuring that irrigation and maintenance practices are optimized for water conservation. (See Guidelines)",
      "The hotel has a linen reuse program for guests staying multiple nights and monitors their participation in the program.",
      "The hotel provides training or guidance on water-saving practices to on-site contractors and staff.",
      "The hotel communicates with guests about its water policy and practices.",
    ],
    guidance: [
      "1. Frameworks may draw from organizations such as WWF Water Risk Filter, WRI Aqueduct, CDP Water Security, or national/local assessments.",
      "4. In high water-risk locations, the hotel establishes water stewardship targets appropriate to the local context.",
      "6. The water policy and practice involve identifying and reducing water losses, such as leaks in pools, tanks, pipelines, and irrigation systems, through monitoring tools and maintenance records.",
    ],
  },
  {
    id: "D3", section: "D", group: "Reducing Pollution", page: 17,
    title: "Greenhouse Gas Emissions",
    statement: "The hotel identifies, measures, and takes steps to avoid or minimize greenhouse gas (GHG) emissions from its operations, and makes an official, public commitment to reducing emissions in support of global decarbonization targets and local strategies.",
    indicators: [
      "The hotel, or its parent group, makes a public commitment to reduce GHG emissions supported by clear targets. (See Guidelines)",
      "The hotel sets annual GHG reduction targets for Scope 1 and Scope 2 aligned with its sustainability management plan.",
      "The hotel tracks its annual greenhouse gas emissions for Scope 1 (direct emissions from fuel use, company vehicles, on-site equipment) and Scope 2 (indirect emissions from purchased electricity, heating, or cooling). (See Guidelines)",
      "The hotel takes actions to avoid and minimize GHG emissions within its own operation.",
      "The hotel reports its GHG emissions in its annual sustainability report. At a minimum, Scope 1 and Scope 2 are reported and disclosed, with Scope 3 reported where feasible and available.",
      "After reducing Scope 1 and 2 emissions—and addressing significant Scope 3 emissions where possible—the hotel offsets some or all of its remaining emissions, based on the size, budget, and capacity of its operations. (See Guidelines)",
      "The hotel has a strategy to phase out harmful coolant gases, transitioning to environmentally friendly alternatives as part of its overall energy conservation and sustainability efforts.",
    ],
    guidance: [
      "1. This may include adopting science-based targets or joining recognized climate action initiatives, such as the Glasgow Declaration on Climate Action in Tourism. Where group-level commitments exist, the hotel ensures that its property-level contribution is clearly reported.",
      "3. Where feasible, the hotel estimates Scope 3 GHG emissions in line with the GHG Protocol. Estimates—based on expenditure, volume, or supplier input—are shared only when confidentiality and legal requirements are met. Progress is evaluated annually, with property-level reporting clearly distinguishable.",
      "6. Offsets are purchased from certified projects (e.g., Gold Standard, Verra, UNFCCC) and used only as a complement to emissions reduction, not a substitute.",
      "Note: The hotel may encourage guests to offset emissions associated with their stay through voluntary programs or carbon-neutral packages.",
    ],
  },
  {
    id: "D4", section: "D", group: "Reducing Pollution", page: 18,
    title: "Transportation",
    statement: "The hotel minimizes transportation needs and increases the use of cleaner and more resource-efficient alternatives by guests, staff, suppliers, and its operations.",
    indicators: [
      "The hotel utilizes the most environmentally friendly and efficient transportation options for its operations.",
      "The hotel provides transportation options such as carsharing or pickups to reduce staff's daily commutes. (See Guidelines)",
      "The hotel provides electric vehicle charging stations (EVCS) for guests and staff, either directly on-site or through agreements with nearby facilities, where a parking lot is provided for guests and staff. (See Guidelines)",
      "The hotel provides bicycle storage or facilities for guests and staff where feasible.",
      "The hotel provides guests with information about alternative transportation options, where applicable. (See Guidelines)",
    ],
    guidance: [
      "2. The hotel may offer incentives for staff, such as public transit subsidies.",
      "3. The availability, type, and number of charging stations are communicated to guests. Where full installation is not feasible, a phased plan or partnership strategy is developed.",
      "5. Transportation information includes locally relevant public transit routes, shared mobility options, and active mobility (walking, cycling). Customers are informed about environmental benefits arising from alternative transport options. Collaboration with local transportation providers or authorities is encouraged.",
    ],
  },
  {
    id: "D5", section: "D", group: "Reducing Pollution", page: 18,
    title: "Wastewater",
    statement: "The hotel ensures that wastewater—including greywater—is effectively managed and treated and is only reused or discharged when it meets safe, best-practice quality standards to ensure no harm to the local population and ecosystems.",
    indicators: [
      "The hotel complies with applicable laws regarding wastewater. (See Guidelines)",
      "The hotel documents evidence of safe discharge in line with legal and environmental requirements.",
      "Where feasible, the hotel implements water-reuse initiatives—such as greywater recycling for non-potable applications or irrigation—to reduce environmental impact and improve water conservation.",
      "The hotel provides technical staff training on wastewater management and compliance with operational guidelines for proper disposal and treatment.",
    ],
    guidance: [
      "1. The hotel may use municipal or government-approved treatment systems or an on-site system that complies with national law and recognized quality standards. The system is periodically tested, and performance is documented and reported.",
    ],
  },
  {
    id: "D6", section: "D", group: "Reducing Pollution", page: 18,
    title: "Solid Waste",
    statement: "The hotel manages solid waste in line with the Waste Hierarchy, aiming to reduce generation, eliminate food waste and single-use plastics, and maximize reuse, recycling, or recovery. Residual waste is managed through legally authorized and environmentally responsible pathways to avoid adverse impacts on the local community and the environment.",
    indicators: [
      "The hotel has a written waste management policy that commits to reducing the amount of waste.",
      "The hotel has a solid waste management plan according to the Waste Hierarchy. The plan includes actions to reduce overall waste and prioritizes reuse, recycling, or recovery of materials. (See Guidelines)",
      "The hotel measures total solid waste produced by type per guest night or per occupied room. (See Guidelines)",
      "The hotel sets annual targets to reduce solid waste generation and tracks progress in line with its waste management plan. (See Guidelines)",
      "The hotel provides basic waste-segregation infrastructure (e.g., recycling bins in common areas) as a minimum requirement. (See Guidelines)",
      "The hotel monitors its use of single-use items and implements actions to eliminate or reduce them, prioritizing high-impact items such as single-use plastics, disposable packaging, and non-reusable guest amenities.",
      "The hotel ensures that all waste not recovered on-site is managed through legally authorized or recognized disposal pathways. (See Guidelines)",
      "The hotel provides regular training and guidance to staff involved in waste-management operations on minimizing waste generation and properly categorizing, sorting, and disposing of waste. Training records and related documentation are maintained.",
      "The hotel provides guidance and information to guests regarding waste minimization practices, as well as proper waste sorting and disposal throughout the property, using clear signage, in-room materials, and/or digital communications.",
    ],
    guidance: [
      "2. Special attention is paid to food waste, construction materials, linens, uniforms, mattresses, and other major waste streams.",
      "3. At minimum, waste is categorized as recyclable materials, food waste, and waste sent to landfill or incineration. Additional categories (e.g., paper, metal, plastic, glass) are added if required by local regulations or operational practice. KPIs are tracked and reported annually.",
      "4. Solid waste generation is evaluated regularly to identify reduction opportunities. Targets and results are reported annually. The hotel’s property-level performance is clearly distinguishable, especially when included within portfolio or corporate reporting.",
      "5. Additional infrastructure (e.g., balers, compactors, digesters/composters) is installed where appropriate to the property’s size and waste volume.",
      "7. The hotel prioritizes responsible and transparent waste management, including specialized handlers for electronic waste, batteries, used cooking oil, and hazardous materials.",
    ],
  },
  {
    id: "D7", section: "D", group: "Reducing Pollution", page: 19,
    title: "Harmful Substances",
    statement: "The hotel minimizes harmful substances in its operations by choosing environmentally friendly products and processes when available. All storage, use, handling, and disposal of chemicals are properly and safely managed.",
    indicators: [
      "The hotel maintains an updated inventory and Safety Data Sheets (SDS) for all harmful substances. (See Guidelines)",
      "The hotel monitors overall chemical usage to identify patterns and opportunities for substitution. (See Guidelines)",
      "The hotel sets targets to increase the replacement of harmful substances with alternatives certified by recognized sustainability standards when available, including for landscaping activities, and reviews progress regularly. (See Guidelines)",
      "The hotel ensures that all chemicals are stored, handled, and disposed of in compliance with relevant safety standards and environmental regulations to prevent chemical pollution.",
      "The hotel provides staff with training and clear guidance on the safe handling, storage, and disposal of chemical products. (See Guidelines)",
      "The hotel informs guests about personal care products and services that are less harmful to the local environment, such as reef-safe sunscreens where relevant, environmentally friendly repellents, or refillable bathroom amenities.",
    ],
    guidance: [
      "1. Safety Data Sheets (SDS) are maintained for cleaning, dishwashing, laundry, sanitizing, pool maintenance, and landscaping chemicals (e.g., pesticides, paints, disinfectants, fertilizers, insecticides, fungicides). SDS are accessible at or near points of use.",
      "2. Where feasible, usage related to guest services is reported per guest night or occupied room. For chemicals used in shared areas, reporting may be based on total volume with contextual notes.",
      "3. Priority is given to products and practices that protect insect biodiversity and minimize ecological disruption.",
      "5. Training includes the identification and use of environmentally preferable alternatives.",
    ],
  },
  {
    id: "D8", section: "D", group: "Reducing Pollution", page: 19,
    title: "Minimize Pollution",
    statement: "The hotel implements practices to minimize pollution from multiple sources—including noise, light, runoff, erosion, ozone-depleting substances, and air, water, and soil contaminants—by identifying potential sources, monitoring impacts, and taking targeted actions to mitigate them.",
    indicators: [
      "The hotel identifies potential sources of pollution based on its location and operational context. (See Guidelines)",
      "The hotel takes measures to prevent and reduce pollution from identified sources under its direct control. (See Guidelines)",
      "The hotel regularly monitors and reviews pollution levels to evaluate the effectiveness of these measures and to support continuous improvement.",
      "When noise pollution sources are identified, the hotel takes steps to manage noise generated by its own operations—particularly from open-air music, fireworks, events, or sound systems—by implementing measures to minimize disturbances to guests and the surrounding community.",
      "The hotel takes steps to minimize light pollution, particularly in protected natural, sensitive, or coastal areas and in their proximity. (See Guidelines)",
      "Smoking may be permitted only in clearly designated outdoor areas or, where legally allowed, in specifically designated indoor smoking rooms that are separated, ventilated, and managed to minimize exposure to non-smokers.",
    ],
    guidance: [
      "1. Potential sources of pollution include noise, light, stormwater runoff, soil erosion, and ozone-depleting substances. Reviews incorporate guest and stakeholder feedback.",
      "2. Pollution sources and mitigation measures may include:\n• Noise: equipment noise limits\n• Light: shielded fixtures, reduced light spill, night-hour dimming\n• Runoff: permeable surfaces, drainage filters\n• Erosion: slope stabilization\n• Ozone-depleting substances: phasing out CFC/HCFC units\n• Air/water/soil contaminants: safe storage and handling\nTargets are documented and available upon request. Pollution minimization is evaluated regularly through reviews or stakeholder feedback to find opportunities for further reduction.",
      "5. Best practices include wildlife-friendly lighting, directional fixtures, dimmers, timers, low-intensity bulbs, and proper shielding to reduce skyglow and ecological disruption.",
    ],
  },
  {
    id: "D9", section: "D", group: "Conserving Biodiversity, Ecosystems and Landscapes", page: 20,
    title: "Biodiversity Conservation",
    statement: "The hotel contributes to biodiversity conservation while minimizing any disruption to natural ecosystems.",
    indicators: [
      "The hotel identifies and documents areas and species in its destination that are legally and/or internationally protected. (See Guidelines)",
      "Where the hotel is located in areas that may directly impact natural protected areas, ecologically sensitive areas, zones of high biodiversity value, or natural habitats, it has a strategy to manage its environmental impacts. (See Guidelines)",
      "The hotel provides and records monetary and/or in-kind contributions to biodiversity conservation. (See Guidelines)",
      "The hotel manages its property to support biodiversity conservation. (See Guidelines)",
      "The hotel prioritizes supporting biodiversity conservation in the areas where it operates, unless urgent conservation needs are identified elsewhere.",
    ],
    guidance: [
      "1. For urban hotels, this includes nearby green spaces or gardens. The hotel documents potential risks or impacts its operations may have on these areas.",
      "2. The strategy includes measures to prevent disturbance, reduce unavoidable impacts, and implement or support restoration or regeneration where required.",
      "3. Examples of collaboration include working with governments, NGOs, conservation coalitions, or local communities to enhance protected areas and establish conservation goals.",
      "4. Practices may include pollinator-friendly landscaping, native vegetation, green roofs, green infrastructure, renewable energy integration, and guest education. Measures are selected based on location and capacity.",
    ],
  },
  {
    id: "D10", section: "D", group: "Conserving Biodiversity, Ecosystems and Landscapes", page: 20,
    title: "Invasive Species",
    statement: "The hotel takes measures to prevent the introduction and spread of invasive species, prioritizing native species wherever feasible.",
    indicators: [
      "The hotel maintains a documented list of invasive plant and animal species relevant to its location and facilities. (See Guidelines)",
      "The hotel works with local authorities or conservation groups to report and remove any detected invasive species promptly.",
      "If the hotel has landscaped areas, gardens, or uses live plants for decoration, it follows landscaping and procurement practices that prevent the introduction and spread of invasive plant species. (See Guidelines)",
      "The hotel maintains an inventory of plants used in its landscaping, identifying those that are native or endemic, and prioritizing those species where feasible. (See Guidelines)",
    ],
    guidance: [
      "1. The hotel assesses potential risks of invasive species spreading into or from the property using credible sources (e.g., IUCN, local authorities, GRIIS). Risks may involve gardens, landscaped areas, basements, storage areas, adjoining buildings, or nearby public spaces.",
      "3. All live plants must be screened and approved against the hotel’s invasive species list before purchase or installation. The hotel may have procedures for monitoring, identification, treatment, and follow-up to ensure effectiveness and prevent unintended impacts.",
      "4. Documentation is updated regularly and used to guide future planting and restoration decisions.",
    ],
  },
  {
    id: "D11", section: "D", group: "Conserving Biodiversity, Ecosystems and Landscapes", page: 21,
    title: "Interactions with Animals",
    statement: "The hotel implements responsible practices that prioritize animal welfare, protect nature, and prevent harm to ecosystems.",
    indicators: [
      "If the hotel offers wildlife tours and visits to natural areas, the hotel ensures that the tour service providers comply with local wildlife regulations and follow responsible practices that prioritize animal welfare, protect nature, and ensure public safety. (See Guidelines)",
      "The hotel establishes and implements safety protocols designed to protect both animals and people during any type of interaction within its directly managed environment. (See Guidelines)",
      "The hotel prohibits all close contact between its visitors and any wild animal within its directly managed environment. This includes feeding, swimming with, touching, holding, or taking close-up photographs.",
      "For destinations where animal interactions are the main tourist activity, the hotel provides guests with clear and accessible information on wildlife conservation and responsible behavior during these activities, encouraging actions that protect animal welfare and natural habitats.",
    ],
    guidance: [
      "1. Internationally recognized standards may include ABTA Animal Welfare Guidelines, WAZA, and Global Humane Society.",
      "2. Protocols may address routine and emergency situations and include disease prevention, supervision, incident response, and measures to prevent distress or harm.",
    ],
  },
  {
    id: "D12", section: "D", group: "Conserving Biodiversity, Ecosystems and Landscapes", page: 21,
    title: "Animal Welfare",
    statement: "The hotel ensures the highest standards of animal welfare for any animals it keeps, owns, or manages, in compliance with relevant laws and regulations and industry best practice guidelines.",
    indicators: [
      "If the hotel owns or manages animals, it must obtain and maintain the necessary licenses or approvals from the relevant government authority or designated agency, where such mechanisms are applicable.",
      "Where animals are temporarily or permanently present at the hotel, their housing, care, and handling comply with local, national, and international regulations. (See Guidelines)",
      "If the hotel keeps or manages animals, it must employ or contract personnel with appropriate qualifications where applicable. (See Guidelines)",
      "The hotel regularly monitors and maintains records on the welfare and well-being of animals in its care. (See Guidelines)",
      "The hotel does not engage in any animal-based practices that compromise animal welfare or well-being, or that coerce animals into unnatural or stressful behaviors. (See Guidelines)",
    ],
    guidance: [
      "2. Compliance aligns with the Five Domains of Animal Welfare and species-specific, science-based standards.",
      "3. Personnel must demonstrate relevant expertise and participate in ongoing training to maintain high standards of animal welfare.",
      "4. Requirements include species-appropriate nutrition, preventive and curative veterinary care, and routine observation of behavior and health.",
      "5. Prohibited practices include animal performances, tactile interactions with infant wild animals, walking with or direct contact with predators or cetaceans, and the use of animals for begging or similar purposes.",
    ],
  },
  {
    id: "D13", section: "D", group: "Conserving Biodiversity, Ecosystems and Landscapes", page: 21,
    title: "Wildlife Harvesting and Trade",
    statement: "The hotel commits to ensuring that wildlife species are never harvested, consumed, displayed, sold, or traded in any illegal or unsustainable manner.",
    indicators: [
      "The hotel maintains a list of nationally protected species, including threatened, endangered, and rare species. (See Guidelines)",
      "The hotel provides guidance to guests and staff not to buy, sell, accept, or use live wildlife, wildlife parts, or derivatives, as souvenirs or otherwise, particularly in destinations located in or near natural protected areas or where wildlife is involved in tourism activities. (See Guidelines)",
      "The hotel does not engage in or support the harvesting, consumption, display, sale, or trade of wildlife species, nor the acquisition or breeding of wild animals, except where such activities are strictly regulated, demonstrably sustainable, and have the explicit approval of the relevant competent authorities.",
    ],
    guidance: [
      "1. Information may be complemented by international frameworks such as CITES and IUCN to ensure alignment with global best practices.",
      "2. Requirements apply to souvenirs and all other uses. Guidance draws from recognized public agencies and organizations (e.g., IUCN Red List, CITES).",
    ],
  },
];
