"""Add GSTC audit requirements: risk assessment, hotel characteristics, cycle tracking

Revision ID: 0a08660c259d
Revises: 0003
Create Date: 2026-10-07 12:49:19.158378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a08660c259d'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('Open', 'InProgress', 'PendingVerification', 'Closed', 'Overdue', name='action_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'Open'::character varying"))
    op.alter_column('actions', 'lag_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OnTrack', 'AtRisk', 'Overdue', name='lag_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'OnTrack'::character varying"))
    op.alter_column('audit_locations', 'is_main_location',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('audit_locations', 'confirmed_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('audit_prompts', sa.Column('auditor_conclusion', sa.Enum('Conform', 'NotConform', 'NotAssessed', name='auditor_conclusion_enum', native_enum=False), nullable=True))
    op.add_column('audit_prompts', sa.Column('evidence_type', sa.String(length=100), nullable=True))
    op.add_column('audit_prompts', sa.Column('evidence_reference', sa.Text(), nullable=True))
    op.add_column('audit_prompts', sa.Column('basis_for_conclusion', sa.Text(), nullable=True))
    op.add_column('audit_prompts', sa.Column('observation_notes', sa.Text(), nullable=True))
    op.add_column('audit_prompts', sa.Column('follow_up_notes', sa.Text(), nullable=True))
    op.alter_column('audit_prompts', 'prompt_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DocumentCheck', 'Interview', 'Observation', 'RecordReview', 'PhotoEvidence', name='prompt_type_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'DocumentCheck'::character varying"))
    op.alter_column('audit_prompts', 'response_status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('Pending', 'C', 'NC', 'OBS', 'FUP', 'TBA', 'NA', name='response_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'Pending'::character varying"))
    op.add_column('audits', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.add_column('audits', sa.Column('country_corruption_index', sa.Integer(), nullable=True))
    op.add_column('audits', sa.Column('risk_level', sa.Enum('HIGH', 'LOW', 'EXTREMELY_LOW', name='risk_level_enum', native_enum=False), nullable=True))
    op.add_column('audits', sa.Column('risk_assessment_date', sa.Date(), nullable=True))
    op.add_column('audits', sa.Column('risk_assessment_notes', sa.Text(), nullable=True))
    op.add_column('audits', sa.Column('has_negative_impacts', sa.Boolean(), nullable=True))
    op.add_column('audits', sa.Column('duration_justification', sa.Text(), nullable=True))
    op.add_column('audits', sa.Column('is_sensitive_area', sa.Boolean(), nullable=False))
    op.add_column('audits', sa.Column('sensitive_area_reason', sa.Text(), nullable=True))
    op.add_column('audits', sa.Column('sensitive_area_coordinates', sa.String(length=100), nullable=True))
    op.add_column('audits', sa.Column('national_legislation_reference', sa.Text(), nullable=True))
    op.add_column('audits', sa.Column('guest_room_count', sa.Integer(), nullable=True))
    op.add_column('audits', sa.Column('staff_count', sa.Integer(), nullable=True))
    op.add_column('audits', sa.Column('has_event_spaces', sa.Boolean(), nullable=False))
    op.add_column('audits', sa.Column('has_function_spaces', sa.Boolean(), nullable=False))
    op.add_column('audits', sa.Column('has_meeting_spaces', sa.Boolean(), nullable=False))
    op.add_column('audits', sa.Column('is_local_ownership', sa.Boolean(), nullable=True))
    op.add_column('audits', sa.Column('has_internet_access', sa.Boolean(), nullable=False))
    op.add_column('audits', sa.Column('certification_start_date', sa.Date(), nullable=True))
    op.add_column('audits', sa.Column('certification_expiry_date', sa.Date(), nullable=True))
    op.add_column('audits', sa.Column('last_on_site_audit_date', sa.Date(), nullable=True))
    op.add_column('audits', sa.Column('last_audit_date', sa.Date(), nullable=True))
    op.add_column('audits', sa.Column('audit_cycle_number', sa.Integer(), nullable=True))
    op.alter_column('audits', 'audit_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Initial', 'Surveillance', 'Recertification', 'FollowUp', name='audit_type_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('audits', 'audit_stage',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DocumentReview', 'SiteAudit', 'FollowUp', name='audit_stage_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'DocumentReview'::character varying"))
    op.alter_column('audits', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Planned', 'InProgress', 'Completed', 'Cancelled', name='audit_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'Planned'::character varying"))
    op.alter_column('control_mappings', 'mapping_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Equivalent', 'Related', 'Supporting', name='mapping_type_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('evidence', 'evidence_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Photo', 'Document', 'Note', 'File', name='evidence_type_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('findings', 'finding_type',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.Enum('MajorNC', 'MinorNC', 'Observation', 'Positive', 'CriticalDocumentReviewFinding', 'NonCriticalDocumentReviewFinding', name='finding_type_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('monitoring_runs', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Open', 'Completed', 'Overdue', 'Cancelled', name='monitoring_run_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'Open'::character varying"))
    op.alter_column('monitoring_tasks', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Low', 'Medium', 'High', 'Extreme', name='monitoring_risk_level_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'Medium'::character varying"))
    op.alter_column('monitoring_tasks', 'importance_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Low', 'Moderate', 'High', 'Critical', name='importance_level_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'Moderate'::character varying"))
    op.alter_column('monitoring_tasks', 'frequency_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Annual', 'Biannual', 'Quarterly', 'Monthly', name='monitoring_frequency_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('monitoring_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Scheduled', 'Due', 'Completed', 'Overdue', 'Suspended', name='monitoring_task_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'Scheduled'::character varying"))
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('Assignment', 'Reminder', 'Escalation', 'VerificationRequest', 'Overdue', name='notification_type_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('process_clause_maps', 'applicability',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Full', 'Partial', 'NotApplicable', name='applicability_type', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'Full'::character varying"))
    op.alter_column('processes', 'category',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Management', 'Operational', 'Support', 'Project', 'Corporate', name='process_category', native_enum=False),
               existing_nullable=False)
    op.alter_column('risk_frequency_rules', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Low', 'Medium', 'High', 'Extreme', name='risk_level_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('risk_frequency_rules', 'frequency_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Annual', 'Biannual', 'Quarterly', 'Monthly', name='frequency_code_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risk_frequency_rules', 'frequency_code',
               existing_type=sa.Enum('Annual', 'Biannual', 'Quarterly', 'Monthly', name='frequency_code_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('risk_frequency_rules', 'risk_level',
               existing_type=sa.Enum('Low', 'Medium', 'High', 'Extreme', name='risk_level_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('processes', 'category',
               existing_type=sa.Enum('Management', 'Operational', 'Support', 'Project', 'Corporate', name='process_category', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('process_clause_maps', 'applicability',
               existing_type=sa.Enum('Full', 'Partial', 'NotApplicable', name='applicability_type', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'Full'::character varying"))
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.Enum('Assignment', 'Reminder', 'Escalation', 'VerificationRequest', 'Overdue', name='notification_type_enum', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('monitoring_tasks', 'status',
               existing_type=sa.Enum('Scheduled', 'Due', 'Completed', 'Overdue', 'Suspended', name='monitoring_task_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'Scheduled'::character varying"))
    op.alter_column('monitoring_tasks', 'frequency_code',
               existing_type=sa.Enum('Annual', 'Biannual', 'Quarterly', 'Monthly', name='monitoring_frequency_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('monitoring_tasks', 'importance_level',
               existing_type=sa.Enum('Low', 'Moderate', 'High', 'Critical', name='importance_level_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'Moderate'::character varying"))
    op.alter_column('monitoring_tasks', 'risk_level',
               existing_type=sa.Enum('Low', 'Medium', 'High', 'Extreme', name='monitoring_risk_level_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'Medium'::character varying"))
    op.alter_column('monitoring_runs', 'status',
               existing_type=sa.Enum('Open', 'Completed', 'Overdue', 'Cancelled', name='monitoring_run_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'Open'::character varying"))
    op.alter_column('findings', 'finding_type',
               existing_type=sa.Enum('MajorNC', 'MinorNC', 'Observation', 'Positive', 'CriticalDocumentReviewFinding', 'NonCriticalDocumentReviewFinding', name='finding_type_enum', native_enum=False),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.alter_column('evidence', 'evidence_type',
               existing_type=sa.Enum('Photo', 'Document', 'Note', 'File', name='evidence_type_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('control_mappings', 'mapping_type',
               existing_type=sa.Enum('Equivalent', 'Related', 'Supporting', name='mapping_type_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('audits', 'status',
               existing_type=sa.Enum('Planned', 'InProgress', 'Completed', 'Cancelled', name='audit_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'Planned'::character varying"))
    op.alter_column('audits', 'audit_stage',
               existing_type=sa.Enum('DocumentReview', 'SiteAudit', 'FollowUp', name='audit_stage_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'DocumentReview'::character varying"))
    op.alter_column('audits', 'audit_type',
               existing_type=sa.Enum('Initial', 'Surveillance', 'Recertification', 'FollowUp', name='audit_type_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('audits', 'audit_cycle_number')
    op.drop_column('audits', 'last_audit_date')
    op.drop_column('audits', 'last_on_site_audit_date')
    op.drop_column('audits', 'certification_expiry_date')
    op.drop_column('audits', 'certification_start_date')
    op.drop_column('audits', 'has_internet_access')
    op.drop_column('audits', 'is_local_ownership')
    op.drop_column('audits', 'has_meeting_spaces')
    op.drop_column('audits', 'has_function_spaces')
    op.drop_column('audits', 'has_event_spaces')
    op.drop_column('audits', 'staff_count')
    op.drop_column('audits', 'guest_room_count')
    op.drop_column('audits', 'national_legislation_reference')
    op.drop_column('audits', 'sensitive_area_coordinates')
    op.drop_column('audits', 'sensitive_area_reason')
    op.drop_column('audits', 'is_sensitive_area')
    op.drop_column('audits', 'duration_justification')
    op.drop_column('audits', 'has_negative_impacts')
    op.drop_column('audits', 'risk_assessment_notes')
    op.drop_column('audits', 'risk_assessment_date')
    op.drop_column('audits', 'risk_level')
    op.drop_column('audits', 'country_corruption_index')
    op.drop_column('audits', 'country_code')
    op.alter_column('audit_prompts', 'response_status',
               existing_type=sa.Enum('Pending', 'C', 'NC', 'OBS', 'FUP', 'TBA', 'NA', name='response_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'Pending'::character varying"))
    op.alter_column('audit_prompts', 'prompt_type',
               existing_type=sa.Enum('DocumentCheck', 'Interview', 'Observation', 'RecordReview', 'PhotoEvidence', name='prompt_type_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'DocumentCheck'::character varying"))
    op.drop_column('audit_prompts', 'follow_up_notes')
    op.drop_column('audit_prompts', 'observation_notes')
    op.drop_column('audit_prompts', 'basis_for_conclusion')
    op.drop_column('audit_prompts', 'evidence_reference')
    op.drop_column('audit_prompts', 'evidence_type')
    op.drop_column('audit_prompts', 'auditor_conclusion')
    op.alter_column('audit_locations', 'confirmed_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('audit_locations', 'is_main_location',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('actions', 'lag_status',
               existing_type=sa.Enum('OnTrack', 'AtRisk', 'Overdue', name='lag_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'OnTrack'::character varying"))
    op.alter_column('actions', 'status',
               existing_type=sa.Enum('Open', 'InProgress', 'PendingVerification', 'Closed', 'Overdue', name='action_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'Open'::character varying"))
    # ### end Alembic commands ###
